name: Build and Deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Check docs folder contents
        run: ls -la docs

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./docs

      - name: Deploy artifact
        uses: actions/deploy-pages@v1

